= Getting Started with Ansible Automation in Red Hat CloudForms
:imagesdir: images
:vernum: 4.7-Beta
:doctype: book
:toc: left
:toclevels: 3
:numbered!:
:experimental:

// Custom attributes
include::common/attributes/cfme.adoc[]

:cfme:

:numbered:


Ansible integrates with {product-title} to provide automation solutions, using playbooks, for Service, Policy and Alert actions. 
Ansible playbooks consist of series of _plays_ or tasks that define automation across a set of hosts,
known as the inventory. 

Ranging from simple to complex tasks, Ansible playbooks can support cloud management:

* *Services* - allow a playbook to back a {product-title_short} service catalog item.
* *Control Actions* - {product-title_short} policies can execute playbooks as actions based on events from providers.
* *Control Alerts* - set a playbook to launch prompted by a {product-title_short} alert.

Ansible is built into {product-title_short} so there is nothing to install. The basic workflow when using Ansible in {product-title} is as follows:

. Enable the *Embedded Ansible* server role.
. Add a source control repository that contains your playbooks.
. Establish credentials with your inventory. 
. Back your services, alerts and policies using available playbooks. 



:leveloffset: 1
include::topics/ .adoc[]


[appendix]
[[appendix]]
:leveloffset: 1
= Appendix

include::common/app-self_signed_CA.adoc[]




